PDF_CV_PATH = "Resume.pdf"
DOCX_PATH = "Document.docx"
EMAIL_SENDER = "chandramoulidas39@gmail.com"
EMAIL_PASSWORD = "hemb iozb hdky gbbh"
EMAIL_RECEIVER = "chandramoulidas39@gmail.com"
BACKEND_URL = "https://moon-gpt.onrender.com/api/chat"