PDF_CV_PATH = "Resume.pdf"
DOCX_PATH = "Document.docx"
EMAIL_SENDER = "chandramoulidas39@gmail.com"
EMAIL_PASSWORD = "hemb iozb hdky gbbh"
EMAIL_RECEIVER = "chandramoulidas39@gmail.com"
BACKEND_URL = "http://127.0.0.1:8000/api/chat"
